version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181:2181"
  
  kafka1:
    image: wurstmeister/kafka:2.13-2.6.0
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.12
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.12:2181
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka:2.13-2.6.0
    ports: 
      - "9093:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.12
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.12:2181
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: wurstmeister/kafka:2.13-2.6.0
    ports: 
      - "9094:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.12
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.12:2181
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock